#!/bin/bash

# Thanks to ideas from:
# https://stackoverflow.com/questions/12499195/git-how-to-find-all-unpushed-commits-for-all-projects-in-a-directory
# https://stackoverflow.com/questions/22735679/list-git-repositories-with-unpushed-changes#

find . -name "*.git" -type d -print0 | xargs -0 -L 1 -i% bash -c "cd %/..; pwd; git status -s -uno; git cherry -v 2>/dev/null"
